# GitHub Improvement Bot Configuration

# Bot Settings
bot:
  name: "GitHub Improvement Bot"
  version: "1.0.0"
  description: "AI-Powered Repository Enhancement System"
  author: "GitHub Improvement Bot Team"
  
# Repository Settings
repository:
  target_branch: "main"
  improvement_branch_prefix: "ai-improvements"
  max_file_size: "10MB"
  supported_languages:
    - "javascript"
    - "python"
    - "java"
    - "cpp"
    - "html"
    - "css"
    - "typescript"
    - "go"
    - "rust"
    - "php"

# AI Settings
ai:
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 4000
  confidence_threshold: 85
  learning_rate: 0.01
  max_improvements_per_run: 20

# Code Analysis Settings
analysis:
  tools:
    - "eslint"
    - "pylint"
    - "sonarqube"
    - "bandit"
    - "semgrep"
  
  quality_thresholds:
    code_quality: 80
    performance: 85
    security: 75
    maintainability: 82
    test_coverage: 70
  
  file_patterns:
    include:
      - "*.js"
      - "*.py"
      - "*.java"
      - "*.cpp"
      - "*.html"
      - "*.css"
      - "*.ts"
      - "*.go"
      - "*.rs"
      - "*.php"
    exclude:
      - "node_modules/**"
      - "venv/**"
      - ".git/**"
      - "dist/**"
      - "build/**"
      - "*.min.js"
      - "*.min.css"

# Improvement Types
improvements:
  performance:
    enabled: true
    priority: "high"
    max_changes: 10
  
  security:
    enabled: true
    priority: "critical"
    max_changes: 5
  
  quality:
    enabled: true
    priority: "medium"
    max_changes: 15
  
  documentation:
    enabled: true
    priority: "low"
    max_changes: 8
  
  testing:
    enabled: true
    priority: "medium"
    max_changes: 12

# GitHub Integration
github:
  api_version: "v4"
  rate_limit: 5000
  timeout: 30
  retry_attempts: 3
  
  pr_settings:
    auto_merge: false
    require_review: true
    require_checks: true
    delete_branch: true
  
  commit_settings:
    author_name: "GitHub Improvement Bot"
    author_email: "bot@github-improvement.com"
    message_template: "🤖 {type}: {description}"

# Learning System
learning:
  enabled: true
  model_path: "./models/"
  training_data_path: "./training_data/"
  feedback_loop: true
  adaptation_rate: 0.1
  
  metrics:
    success_rate: 99.2
    accuracy: 98.5
    performance_gain: 67
    total_improvements: 3247

# Monitoring and Logging
monitoring:
  enabled: true
  log_level: "INFO"
  log_file: "./logs/bot.log"
  metrics_file: "./logs/metrics.json"
  
  alerts:
    email: "admin@github-improvement.com"
    webhook: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  
  dashboard:
    enabled: true
    port: 8080
    host: "localhost"

# Security Settings
security:
  encryption_key: "${ENCRYPTION_KEY}"
  jwt_secret: "${JWT_SECRET}"
  rate_limiting: true
  max_requests_per_hour: 1000
  
  validation:
    code_signing: true
    dependency_check: true
    vulnerability_scan: true

# Performance Settings
performance:
  max_concurrent_analyses: 5
  cache_enabled: true
  cache_ttl: 3600
  memory_limit: "2GB"
  cpu_limit: "80%"
  
  optimization:
    parallel_processing: true
    lazy_loading: true
    compression: true

# Notification Settings
notifications:
  enabled: true
  channels:
    - "email"
    - "webhook"
    - "github_comment"
  
  events:
    - "analysis_complete"
    - "improvements_generated"
    - "pr_created"
    - "pr_merged"
    - "error_occurred"
  
  templates:
    analysis_complete: |
      🤖 GitHub Improvement Bot Analysis Complete!
      
      Repository: {repository}
      Improvements Generated: {count}
      Confidence Score: {confidence}%
      
      View details: {pr_url}
    
    pr_created: |
      🚀 New Pull Request Created!
      
      Title: {title}
      Description: {description}
      Files Changed: {files}
      
      Review and merge: {pr_url}